# Generated by Django 3.0.3 on 2021-06-20 19:31
import logging
from datetime import date

from django.db import migrations
from policy.models import Policy

from policy_notification.models import IndicationOfPolicyNotifications
from policy_notification.utils import get_default_notification_data

logger = logging.getLogger(__name__)

defaults = get_default_notification_data()


def __create_existing_policies_indications(policy):
    indication = IndicationOfPolicyNotifications(
        activation_of_policy=date.min,
        renewal_of_policy=date.min,
        policy=policy,
    )
    return indication


def add_defaults_family_notification_approval(apps, schema_editor):
    policies = Policy.objects.filter(validity_to=None).iterator()
    IndicationOfPolicyNotifications.objects.bulk_create(
        (__create_existing_policies_indications(policy) for policy in policies)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0007_auto_20211017_1246')
    ]

    operations = [
        migrations.RunPython(add_defaults_family_notification_approval, reverse_code=migrations.RunPython.noop)
    ]

