# Generated by Django 3.0.3 on 2021-06-20 19:31
import logging
from datetime import date

from django.db import migrations
from policy.models import Policy
from django.conf import settings

from policy_notification.models import IndicationOfPolicyNotifications
from policy_notification.utils import get_default_notification_data

logger = logging.getLogger(__name__)

defaults = get_default_notification_data()

mssql_code = """
insert into 
tblIndicationOfPolicyNotifications(PolicyId, ValidityFrom, NotificationOnActivationSent, NotificationOnRenewalSent)    
select PolicyID, GETDATE(), '0001-01-01 00:00:00.000', '0001-01-01 00:00:00.000'  from tblPolicy 
where ValidityTo is null and PolicyID not in (select PolicyID from tblIndicationOfPolicyNotifications)
"""

psql_code = """
insert into 
"tblIndicationOfPolicyNotifications"("PolicyID", "ValidityFrom", "NotificationOnActivationSent", "NotificationOnRenewalSent")    
select "PolicyID", CURRENT_TIMESTAMP, '0001-01-01 00:00:00.000', '0001-01-01 00:00:00.000'  from "tblPolicy" 
where "ValidityTo" is null and "PolicyID" not in (select "PolicyID" from "tblIndicationOfPolicyNotifications")
"""


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0007_auto_20211017_1246')
    ]

    operations = [
        migrations.RunSQL(mssql_code if settings.MSSQL else psql_code)
    ]

