# Generated by Django 3.2.18 on 2023-06-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0010_auto_20211019_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familynotification',
            options={'managed': True},
        ),
    ]
