# Generated by Django 3.2.18 on 2023-06-20 11:13

from django.db import migrations
from django.conf import settings

from policy_notification.utils import get_default_notification_data

defaults = get_default_notification_data()

default_language = defaults['languageOfNotification']

pssql_create_tblFamilySMS = """
CREATE TABLE "tblFamilySMS" 
("ValidityFrom" timestamp with time zone NOT NULL,
"ValidityTo" timestamp with time zone NULL,
"FamilyID" integer NOT NULL PRIMARY KEY,
"ApprovalOfSMS" boolean NOT NULL,
"LanguageOfSMS" varchar(5) NOT NULL);
ALTER TABLE "tblFamilySMS" 
ADD CONSTRAINT "tblFamilySMS_FamilyID_e9356429_fk_tblFamilies_FamilyID" FOREIGN KEY ("FamilyID")
REFERENCES "tblFamilies" ("FamilyID")
DEFERRABLE INITIALLY DEFERRED;
"""

pssql_insert_tblFamilySMS = f"""
insert into 
"tblFamilySMS"("FamilyID", "ValidityFrom", "ApprovalOfSMS", "LanguageOfSMS")    
select "FamilyID", CURRENT_TIMESTAMP, False, '{default_language}' from "tblFamilies" 
where "ValidityTo" is null and "FamilyID" not in (select "FamilyID" from "tblFamilySMS")
"""


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0010_auto_20211019_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familynotification',
            options={'managed': True},
        ),
        migrations.RunSQL("select 1" if settings.MSSQL else pssql_create_tblFamilySMS),
        migrations.RunSQL("select 1" if settings.MSSQL else pssql_insert_tblFamilySMS)
    ]
