# Generated by Django 3.0.3 on 2021-06-20 19:31
import logging

from django.db import migrations
from insuree.models import Family
from django.conf import settings

from policy_notification.models import FamilyNotification
from policy_notification.utils import get_default_notification_data

logger = logging.getLogger(__name__)

defaults = get_default_notification_data()

default_approval = defaults['approvalOfNotification']
default_language = defaults['languageOfNotification']

mssql_code = f"""
insert into 
tblFamilySMS(FamilyID, ValidityFrom, ApprovalOfSMS, LanguageOfSMS)    
select FamilyId, GETDATE(), 0, '{default_language}' from tblFamilies 
where ValidityTo is null and FamilyID not in (select FamilyID from tblFamilySMS)
"""

psql_code = f"""
insert into 
"tblFamilySMS"("FamilyID", "ValidityFrom", "ApprovalOfSMS", "LanguageOfSMS")    
select "FamilyID", CURRENT_TIMESTAMP, False, '{default_language}' from "tblFamilies" 
where "ValidityTo" is null and "FamilyID" not in (select "FamilyID" from "tblFamilySMS")
"""

class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0011_alter_familynotification_options')
    ]

    operations = [
        migrations.RunSQL(mssql_code if settings.MSSQL else psql_code)
    ]

