# Generated by Django 4.2.11 on 2024-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_notification', '0011_create_family_sms_and_alter_notification'),
        ('insuree', '0021_family_uuid')
    ]

    def update_uuid(app, schema_editor):
        PolicyNotification = app.get_model('policy_notification', 'FamilyNotification')
        Family = app.get_model('insuree', 'family')

        # Update family_uuid in policy
        for notification in PolicyNotification.objects.all():
            if notification.family:
                family = Family.objects.filter(id=notification.family.id).first()
                if family:
                    notification.family_uuid = family.uuid
                    notification.save()

    operations = [
        migrations.AddField(
            model_name='familynotification',
            name='family_uuid',
            field=models.UUIDField(blank=True, db_column='FamilyUUID', null=True),
        ),
        migrations.RunPython(update_uuid)
    ]
