# Generated by Django 4.2.11 on 2024-06-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_remove_familymutation_family_uuid_and_more'),
        ('policy_notification', '0013_alter_familynotification_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familynotification',
            name='family',
        ),
        migrations.RenameField(
            model_name='familynotification',
            old_name='family_uuid',
            new_name='family'
        ),
        migrations.AlterField(
            model_name='familynotification',
            name='family',
            field=models.ForeignKey(db_column='FamilyUUID', on_delete=django.db.models.deletion.DO_NOTHING,
                                    primary_key=True, related_name='family_notification', serialize=False, to='insuree.family'),
        ),
    ]
